### ISSUE TITLE
Revert Commits

### ISSUE THREAD

**Issue by zamora-UBC** [brandongk-ubco/gitstats#92]
Hello,

I noticed that git revert commits still count as a grade for changes and it makes it double. First for the error and then for reverting. This messes up the grading tremendously, the only way around this is to re-write git history, which is bad practice and not possible for protected branches. 

I really do not know if it is a problem that could be addressed but it would definitely help for mistakes in commits that shouldn't count as part of a member's grade. 

Thank you!

**Comment by brandongk-ubco** [comment]
Hi Zamora,

Thanks for reporting this issue.  I believe you are correct on current behaviour.  Since the revert is also a commit, it would be counted as well.  I agree that rebasing or some other form of history re-writing is very bad practice for common branches.

As a ballpark, how many revert commits did your team create this week, and what was the impact on the final scores?  I think revert commits would have only a minor affect the number of contributions and number commits when calculating effort scores.

Thanks,

Brandon

**Comment by zamora-UBC** [comment]
Hi Brandon,

Thank you for responding. I only did one revert commit. The revert commit of my error caused 224 changes in total, which brought my teammates grade of changes down to 17, 32 and 16. Their final grades were 46, 58, and 46. I agree that for commit grades shouldn't be as big of a problem, but it looks like for changes it is. Maybe, it was another factor that actually made the grades so low but it looks like changes was a big part of it. 

I also thought the the additions and deletions were calculated by pr and not by each commit. Because my pr was still +0,-0 but the commits did have changes, which were the ones that caused did grade disparity. 

Thank you for your response and attention!

Cheers, 

Gerardo Zamora.

**Comment by brandongk-ubco** [comment]
224 changes is not very many... for that number to be significant, there probably weren't many changes made that week in total.  We are also making some tweaks to how changes are calculated in #94 - this should help downplay these situations even further.

For the PR, did you close it or merge it?  I am asking because there have been suggestions around how to handle closed vs. merged PRs.

I don't think we can calculate additions and deletions per PR, as the author is defined at the commit level.  If we look only at the PR level, how do we know who wrote the code??

**Comment by brandongk-ubco** [comment]
@zamora-UBC - #94 is released.  Are you expecting any further action on this issue, or can it be closed?

**Comment by zamora-UBC** [comment]
Thank you so much Brandon. Yes it can be closed. I didn't want to close it because I don't know if I was allowed.

Thank you again!
