### ISSUE TITLE
Issues are flagged as mislabelled if they have multiple labels

### ISSUE THREAD

**Issue by merelister** [brandongk-ubco/gitstats#99]
An issue should be valid as long as it includes either the chore or task label, as sometimes the chore or task label alone is too broad.
cc @rachellegelden @Parsa-Rajabi

**Comment by brandongk-ubco** [comment]
@merelister @rachellegelden @Parsa-Rajabi

This is by design.  Chores and tasks are mutually exclusive by definition.  A task is work towards a feature, which is client motivated and delivers business value.  A chore is motivated by developers, and is primarily for improving speed of development over the life of the project.  Examples of chores are building the CI system, refactoring code, or implementing a code linter.  Examples of things that are NOT chores are writing tests or documentation; these are requirements towards a task.

It is possible that a small amount of chore work is included in a PR for a task, but this should generally be discouraged.  If you find that there are truly two things in a PR, you have two options: split the PR into 2 (best, but slow) or merge it and learn for next time.  The one you pick is up to your team to decide.

If you do merge a PR that has a chore and a task (or multiple tasks, or multiple chores, or multiple explorations) then I suggest you log it as two (or more) independent issues and close them each/all.  The team score is based on how many of these issues you close in a time period, so it's actually to your benefit to count them as two independent issues, even if they end up in the same PR.

**Comment by rachellegelden** [comment]
@brandongk 

That definitely makes sense, an issue that is both a chore and a task is too large of an issue and should be broken down. We meant to say that while chore and task should be mutually exclusive from each other, it would be nice if would be able to add other various labels to the issues. 

An example of when we would want to use more than one label would be if we are working on fixing a part of a feature that has a bug, we would like to use both the "task" and "bug" labels. Or if we are uploading documentation, we would want to label the issue with both "chore" and "documentation" labels. 

This would help keep our Project Board more organized and issues much more accurate.

**Comment by brandongk-ubco** [comment]
@rachellegelden - This makes sense, sorry I misunderstood.  I put up #103 with this implemented.  I'll make sure it makes it into the next release.

**Comment by brandongk-ubco** [comment]
@rachellegelden @Parsa-Rajabi @merelister - This is released in v1.0.8 (https://github.com/brandongk-ubco/gitstats/releases/tag/v1.0.8)
